export const PHOTOS_FETCHED = 'PHOTOS_FETCHED';
export const PHOTOS_UPLOADED = 'PHOTOS_UPLOADED';
export const ALL_PHOTOS_DELETED = 'ALL_PHOTOS_DELETED';
export const DELETE_UPLOADED_PHOTO = 'DELETE_UPLOADED_PHOTO';
export const UPDATE_UPLOADED_PHOTO = 'UPDATE_UPLOADED_PHOTO';
